version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "8080:8080"
      - "5173:5173"
    depends_on:
      - db
      - redis
  db:
    image: postgres
    container_name: chess-db
    restart: always
    environment:
      - POSTGRES_PASSWORD=pass
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data 
  
  redis:
    image: redis
    container_name: chess-redis
    ports:
      - "6379:6379"


volumes:
  postgres-data: 